name: github-action-runner-reference-docker
on:
  workflow_dispatch:
  
# remove all permission, just checking whats on the runner  
permissions: {}

defaults:
  run:
    # when the `shell` is explicitly set, the following options are automically applied:
    #    `set -eo pipefail`
    # These options are NOT applied by default (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)
    # 
    # The output of `ps faux` on linux shows that the .bash_profile and .bashrc file is ignored
    # ps faux ==> /usr/bin/bash --noprofile --norc -e -o pipefail <job script>.sh
    shell: bash

env:
  # just for fun
  HELLO: world
  
jobs:
  dump-it-out:
    name: "${{ matrix.os}} docker dump out"
    runs-on: ${{ matrix.os }} 

    strategy:

      matrix:
        os:
          - ubuntu-22.04
   
    steps:
     - name: do all the docker things
       run: |
       
         # setup QEMU
         docker run --privileged --rm tonistiigi/binfmt --install all
         
         
         cat >> $GITHUB_STEP_SUMMARY <<EOF
         # ImageOS/ImageVersion: ${ImageOS}/${ImageVersion}
         begin
         
         EOF
        
         cat >> $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ### docker version
         
         ```console
         OPEN_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker version
         $(docker version)
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
 

         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ### docker images
         
         ```console
         OPEN_FENCE
 
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker images
         $(docker images)
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ### docker buildx ls num 1
         
         ```console
         OPEN_FENCE
 
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker buildx ls
         $(docker buildx ls)
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ### create a docker-container builder
         
         ```console
         OPEN_FENCE
 
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker buildx create \
           --use \
           --name container \
           --driver-opt network=host \
           --driver docker-container \
           --bootstrap
         $(docker buildx create \
             --use \
             --name container \
             --driver-opt network=host \
             --driver docker-container \
             --bootstrap)
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ### docker buildx ls num 2
         
         ```console
         OPEN_FENCE
 
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker buildx ls
         $(docker buildx ls)
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         
         # in order to build multi-arch all at once, you need to push to a registry first
         # the github actions from docker push to ghcr but i don't want to do that just for quick testing
         docker run --rm -d -p 5000:5000 --name registry registry:2
         
         echo ""
         echo "DOCKER PS"
         docker ps -a
         
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ## build multi platform image
         
         ```console
         OPEN_FENCE
 
         tee -a $GITHUB_STEP_SUMMARY <<'BUILD'
         $ docker buildx build \
             --tag localhost:5000/deric4/gha-reference \
             --push \
             --platform linux/amd64,linux/arm64 . \
             -f-<<'EOF'
               FROM debian:latest
               CMD echo "\n\n\tIN CONTAINER\n\tarch: $(dpkg --print-architecture)\n\n"
             EOF
         BUILD
         tee -a $GITHUB_STEP_SUMMARY <<BUILD
         $(
            docker buildx build \
               --tag localhost:5000/deric4/gha-reference \
               --push \
               --platform linux/amd64,linux/arm64 . \
               -f-<<'EOF'
                 FROM debian:latest
                 CMD echo "\n\n\tIN CONTAINER\n\tarch: $(dpkg --print-architecture)\n\n"
               EOF
         )
         BUILD
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         echo ""
         echo "DOCKER RUN 1 --platform linux/amd64"
         docker run \
           --platform linux/amd64 \
           --rm \
           localhost:5000/deric4/gha-reference
           
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ## docker run linux/amd64
         :note: check workflow file for ommitted previous steps for setting up a local registry
         ```console
         OPEN_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker run \
           --platform linux/amd64 \
           --rm \
           localhost:5000/deric4/gha-reference
         $(
           docker run \
             --platform linux/amd64 \
             --rm \
             localhost:5000/deric4/gha-reference
         )
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         <details>
         <summary>
         
         ### docker inspect linux/amd64
         
         </summary>
         
         ```console
         OPEN_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker image inspect 'localhost:5000/deric4/gha-reference:latest'
         $(docker image inspect 'localhost:5000/deric4/gha-reference:latest')
         EOF
         
         cat >> $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         </details>
         CLOSE_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         ## docker run linux/amd64
         :note: check workflow file for ommitted previous steps for setting up a local registry
         
         ```console
         OPEN_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker run \
           --platform linux/amd64 \
           --rm \
           localhost:5000/deric4/gha-reference
         $(
           docker run \
             --platform linux/arm64 \
             --rm \
             localhost:5000/deric4/gha-reference
         )
         EOF
         
         tee -a $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         CLOSE_FENCE
         
         tee -a $GITHUB_STEP_SUMMARY <<'OPEN_FENCE'
         <details>
         <summary>
         
         ### docker inspect linux/arm64
         
         </summary>
         
         ```console
         OPEN_FENCE
         tee -a $GITHUB_STEP_SUMMARY <<EOF
         $ docker image inspect 'localhost:5000/deric4/gha-reference:latest'
         $(docker image inspect 'localhost:5000/deric4/gha-reference:latest')
         EOF
         
         cat >> $GITHUB_STEP_SUMMARY <<'CLOSE_FENCE'
         ```
         
         </details>
         CLOSE_FENCE
